[theme]
base="light"
primaryColor="#d48076"
backgroundColor="white"
secondaryBackgroundColor="powderBlue"
baseRadius="full"
showWidgetBorder=false
dataframeHeaderBackgroundColor="#d7eff2"

[theme.sidebar]
baseRadius="10px"
borderColor="black"
